GET http://localhost:3001/api/persons
###
GET http://localhost:3001/info
###
GET http://localhost:3001/api/persons/653d1c1083e60848deb245f6
###
DELETE http://localhost:3001/api/persons/653d27e29aec1a5d5dae1e9e
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Mel",
    "number": "1000"
}
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Ada Lovelace",
    "number": "00-139004"
}
###
PUT http://localhost:3001/api/persons/653d2282ea24ef5d21589bc5
Content-Type: application/json

{
    "name": "Alm",
    "number": "10000000-1"
}